global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: "client_exporter"
    static_configs:
      - targets: ["exporter:8001"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]